In [ ]:
#mount drive dan membaca data
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
path = '/content/drive/MyDrive/FOLDER/DATASET.xlsx'
df = pd.read_excel(path)
df

,A,B,C,D,E,F,G,H,R,I,S,J,T,U,V,W,K,L,KA
0,126.391500,42.482300,90.4589,30.014800,42.1094,21.760500,10.4828,13.490700,24.937000,19.157500,34.1556,2.503800,10.0555,6.2820,10.9057,13.324200,9.8579,8.986000,89.727727
1,123.586300,42.546500,91.2391,28.003200,43.3098,22.308400,10.3367,12.939600,28.782000,19.112700,35.1719,2.485200,10.7744,6.6252,10.7242,13.169500,9.8783,9.019600,91.089769
2,118.413100,42.309800,91.7904,28.003200,45.7016,24.062700,10.0320,12.450900,30.973600,18.738500,36.4611,2.448000,11.5661,6.7572,10.8150,13.026700,9.7100,8.969200,92.070960
3,127.707400,43.679600,95.0539,29.281600,49.3554,27.300300,15.5259,16.503700,67.666500,30.242200,43.3624,6.551200,15.0605,8.0420,21.8780,18.722900,27.7551,11.490400,92.404762
4,127.118600,46.162200,97.9987,29.488400,56.7278,28.735400,28.2603,29.807000,129.625100,50.777800,53.5022,9.999600,23.5781,10.7612,36.8732,28.480900,47.3510,15.081800,91.236363
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,226.009800,93.803800,179.6756,38.710800,71.2932,34.906100,15.5687,18.318600,110.701000,33.749900,50.0816,6.833900,24.3971,10.9372,37.3800,41.674800,38.3562,14.601100,92.739674
96,237.432500,95.245700,183.7478,37.854500,71.4491,35.606000,15.6753,19.130300,120.227600,34.836400,50.9695,7.150500,25.2343,11.1220,37.5154,41.424200,39.4805,14.929700,92.550197
97,224.143800,91.092800,184.5989,35.946200,65.8610,32.222900,15.5113,18.398700,107.824000,34.716700,50.3198,7.030000,24.3061,10.8052,37.5431,43.057500,38.3743,14.449800,92.015762
98,250.754582,98.756564,193.6922,40.910291,79.7453,40.724264,15.9787,20.267927,125.469009,36.147345,51.2400,7.284918,25.4982,11.2332,38.8177,42.942645,41.4521,15.267991,93.445480
99,224.320000,92.790300,180.0576,37.882800,70.3721,35.342200,15.8762,19.882300,124.390000,36.108900,51.4982,7.414300,25.6529,11.4122,37.8318,40.078200,40.8605,15.157200,92.471479

In [ ]:
#Import library
import os
import random
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import (mean_squared_error, mean_absolute_percentage_error, r2_score)

In [ ]:
#Korelasi channel dg target
korelasi = df.corr()['Y'].sort_values(ascending=False).drop('Y')
print (korelasi)

C    0.236911
E    0.224220
B    0.223788
F    0.198612
L    0.179782
G    0.167442
I    0.164224
A    0.133551
H    0.115204
D    0.040524
U    0.009317
T    0.005070
K   -0.012330
S   -0.022247
W   -0.077710
R   -0.109717
J   -0.114501
V   -0.167560
Name: KA, dtype: float64

In [ ]:
# Seleksi berdasarkan nilai absolut korelasi
korelasi = df.corr()['Y'].sort_values(ascending=False).drop('Y')
corr_sorted = korelasi.reindex(
korelasi.abs().sort_values(ascending=False).index)

print("Ranking Var X:")
print(corr_sorted.abs())

Ranking Channel:
C    0.236911
E    0.224220
B    0.223788
F    0.198612
L    0.179782
V    0.167560
G    0.167442
I    0.164224
A    0.133551
H    0.115204
J    0.114501
R    0.109717
W    0.077710
D    0.040524
S    0.022247
K    0.012330
U    0.009317
T    0.005070
Name: KA, dtype: float64

In [ ]:
# Define x dan y
X = df.drop(columns=['Y'])
y = df['Y']
display(df)

# Reproducible
SEED = 42
np.random.seed(SEED)
random.seed(SEED)

#k fold
kf = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42)

# Save root
root_save = '/content/drive/MyDrive/Folder/Hasil Predict'
os.makedirs(root_save, exist_ok=True)

,A,B,C,D,E,F,G,H,R,I,S,J,T,U,V,W,K,L,KA
0,126.391500,42.482300,90.4589,30.014800,42.1094,21.760500,10.4828,13.490700,24.937000,19.157500,34.1556,2.503800,10.0555,6.2820,10.9057,13.324200,9.8579,8.986000,89.727727
1,123.586300,42.546500,91.2391,28.003200,43.3098,22.308400,10.3367,12.939600,28.782000,19.112700,35.1719,2.485200,10.7744,6.6252,10.7242,13.169500,9.8783,9.019600,91.089769
2,118.413100,42.309800,91.7904,28.003200,45.7016,24.062700,10.0320,12.450900,30.973600,18.738500,36.4611,2.448000,11.5661,6.7572,10.8150,13.026700,9.7100,8.969200,92.070960
3,127.707400,43.679600,95.0539,29.281600,49.3554,27.300300,15.5259,16.503700,67.666500,30.242200,43.3624,6.551200,15.0605,8.0420,21.8780,18.722900,27.7551,11.490400,92.404762
4,127.118600,46.162200,97.9987,29.488400,56.7278,28.735400,28.2603,29.807000,129.625100,50.777800,53.5022,9.999600,23.5781,10.7612,36.8732,28.480900,47.3510,15.081800,91.236363
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,226.009800,93.803800,179.6756,38.710800,71.2932,34.906100,15.5687,18.318600,110.701000,33.749900,50.0816,6.833900,24.3971,10.9372,37.3800,41.674800,38.3562,14.601100,92.739674
96,237.432500,95.245700,183.7478,37.854500,71.4491,35.606000,15.6753,19.130300,120.227600,34.836400,50.9695,7.150500,25.2343,11.1220,37.5154,41.424200,39.4805,14.929700,92.550197
97,224.143800,91.092800,184.5989,35.946200,65.8610,32.222900,15.5113,18.398700,107.824000,34.716700,50.3198,7.030000,24.3061,10.8052,37.5431,43.057500,38.3743,14.449800,92.015762
98,250.754582,98.756564,193.6922,40.910291,79.7453,40.724264,15.9787,20.267927,125.469009,36.147345,51.2400,7.284918,25.4982,11.2332,38.8177,42.942645,41.4521,15.267991,93.445480
99,224.320000,92.790300,180.0576,37.882800,70.3721,35.342200,15.8762,19.882300,124.390000,36.108900,51.4982,7.414300,25.6529,11.4122,37.8318,40.078200,40.8605,15.157200,92.471479

In [ ]:
# LOOP KFOLD dan
hasil = []
for n_x in range(1, 10):
    top_x = corr_sorted.index[:n_x].tolist()
    print(f"{n_x} Var X")
    print(f"FITUR : {', '.join(top_var x)}")

    #simpan data
    hasil_fold = []
    fold_train = []
    fold_test = []
    actual_train = []
    pred_train = []
    actual_test = []
    pred_test = []

    #Loop k fold
    for fold, (train_idx, test_idx) in enumerate(kf.split(X), start=1):

        X_train = X.iloc[train_idx][top_x]
        X_test = X.iloc[test_idx][top_x]
        y_train = y.iloc[train_idx]
        y_test = y.iloc[test_idx]

        # Fit model
        model = LinearRegression()
        model.fit(X_train, y_train)

        # Prediksi y train & test
        y_pred_train = model.predict(X_train)
        y_pred_test = model.predict(X_test)

        # Metrik Train
        train_mse = mean_squared_error(y_train, y_pred_train)
        train_rmse = np.sqrt(train_mse)
        train_mape = mean_absolute_percentage_error(y_train, y_pred_train)*100
        train_r2 = r2_score(y_train, y_pred_train)

        # Metrik Test
        test_mse = mean_squared_error(y_test, y_pred_test)
        test_rmse = np.sqrt(test_mse)
        test_mape = mean_absolute_percentage_error(y_test, y_pred_test)*100
        test_r2 = r2_score(y_test, y_pred_test)

        # Persamaan Tiap fold
        persamaan_fold = f"y = {model.intercept_:.6f}"
        for nama, coef in zip(top_channels, model.coef_):
            if coef >= 0:
               persamaan_fold += f" + ({coef:.6f})*{nama}"
            else:
               persamaan_fold += f" - ({abs(coef):.6f})*{nama}"

        print(f"\n===== {n_channel} CHANNEL | FOLD {fold} =====")
        print("\n--- TRAIN ---")
        print(f"R2 score    : {train_r2score:.4f}")
        print(f"RMSE        : {train_rmse:.4f}")
        print(f"MSE         : {train_mse:.4f}")
        print(f"MAPE        : {train_mape:.4f}")
        print(f"Adj_R2      : {train_adj_r2:.4f}")

        print("\n--- TEST ---")
        print(f"R2 score    : {test_r2score:.4f}")
        print(f"RMSE        : {test_rmse:.4f}")
        print(f"MSE         : {test_mse:.4f}")
        print(f"MAPE        : {test_mape:.4f}")
        print(f"Adj_R2      : {test_adj_r2:.4f}")
        print("\nPersamaan:")
        print(persamaan_fold)

    #GRAFIK ACTUAL VS PREDIKSI
    # TRAIN + TEST
    plt.figure(figsize=(7,7))
    plt.scatter(
        actual_train,
        pred_train,
        color='blue',
        alpha=0.8,
        label='Train',
        edgecolors='k')
    plt.scatter(
        actual_test,
        pred_test,
        color='orange',
        alpha=0.8,
        label='Test',
        edgecolors='k')
    min_val = min(
              min(actual_train), min(actual_test),
              min(pred_train), min(pred_test))
    max_val = max(
              max(actual_train), max(actual_test),
              max(pred_train), max(pred_test))
    plt.plot(
        [min_val, max_val],
        [min_val, max_val],
        'r--',
        linewidth=2,
        label='Perfect Prediction')

    plt.xlim(min_val-0.5, max_val+0.5)
    plt.ylim(min_val-0.5, max_val+0.5)
    plt.xlabel('Aktual Y')
    plt.ylabel('Prediksi Y')
    plt.title(f'Aktual vs Prediksi {n_x}')
    plt.legend()
    plt.grid(True)
    plt.savefig(
    f"{root_save}/{n_channel}_channel/actual_vs_predicted_train_test.png",
    dpi=300,
    bbox_inches='tight')
    plt.close()

    #Hasil fold
    hasil_fold_df = pd.DataFrame(hasil_fold)
    hasil_fold_df.to_excel(
    f"{root_save}/{n_channel}_channel/hasil_fold.xlsx",
    index=False)
    hasil.extend(hasil_fold)

# HASIL AKHIR
hasil_df = pd.DataFrame(hasil)
hasil_df.to_excel(
    f"{root_save}/hasil_mlr_n_x.xlsx",
    index=False)
hasil_df

1 CHANNEL
FITUR : C

===== 1 CHANNEL | FOLD 1 =====

--- TRAIN ---
R           : 0.2097
R2          : 0.0440
R2 score    : 0.0440
RMSE        : 1.0338
MSE         : 1.0688
MAPE        : 0.8845
Adj_R2      : 0.0317

--- TEST ---
R           : 0.3417
R2          : 0.1167
R2 score    : 0.0824
RMSE        : 0.7549
MSE         : 0.5699
MAPE        : 0.6600
Adj_R2      : 0.0314

Persamaan:
y = 90.451459 + (0.006472)*C

===== 1 CHANNEL | FOLD 2 =====

--- TRAIN ---
R           : 0.2393
R2          : 0.0573
R2 score    : 0.0573
RMSE        : 0.9621
MSE         : 0.9256
MAPE        : 0.7961
Adj_R2      : 0.0452

--- TEST ---
R           : 0.2683
R2          : 0.0720
R2 score    : 0.0407
RMSE        : 1.0701
MSE         : 1.1450
MAPE        : 1.0034
Adj_R2      : -0.0126

Persamaan:
y = 90.348437 + (0.007373)*C

===== 1 CHANNEL | FOLD 3 =====

--- TRAIN ---
R           : 0.2612
R2          : 0.0682
R2 score    : 0.0682
RMSE        : 0.9559
MSE         : 0.9138
MAPE        : 0.8334
Adj_R2      : 0.0563

--- TEST ---
R           : 0.1588
R2          : 0.0252
R2 score    : -0.0065
RMSE        : 1.0919
MSE         : 1.1923
MAPE        : 0.8777
Adj_R2      : -0.0624

Persamaan:
y = 90.229844 + (0.007721)*C

===== 1 CHANNEL | FOLD 4 =====

--- TRAIN ---
R           : 0.2246
R2          : 0.0504
R2 score    : 0.0504
RMSE        : 0.9647
MSE         : 0.9306
MAPE        : 0.8290
Adj_R2      : 0.0383

--- TEST ---
R           : 0.2749
R2          : 0.0756
R2 score    : 0.0594
RMSE        : 1.0588
MSE         : 1.1211
MAPE        : 0.8900
Adj_R2      : 0.0071

Persamaan:
y = 90.405114 + (0.006505)*C

===== 1 CHANNEL | FOLD 5 =====

--- TRAIN ---
R           : 0.2520
R2          : 0.0635
R2 score    : 0.0635
RMSE        : 0.9978
MSE         : 0.9956
MAPE        : 0.8516
Adj_R2      : 0.0515

--- TEST ---
R           : 0.1747
R2          : 0.0305
R2 score    : 0.0175
RMSE        : 0.9272
MSE         : 0.8597
MAPE        : 0.7887
Adj_R2      : -0.0370

Persamaan:
y = 90.250488 + (0.007772)*C
2 CHANNEL
FITUR : C, E

===== 2 CHANNEL | FOLD 1 =====

--- TRAIN ---
R           : 0.2513
R2          : 0.0632
R2 score    : 0.0632
RMSE        : 1.0234
MSE         : 1.0473
MAPE        : 0.8716
Adj_R2      : 0.0388

--- TEST ---
R           : 0.3659
R2          : 0.1339
R2 score    : 0.1012
RMSE        : 0.7471
MSE         : 0.5582
MAPE        : 0.6838
Adj_R2      : -0.0045

Persamaan:
y = 89.726605 + (0.004244)*C + (0.017614)*E

===== 2 CHANNEL | FOLD 2 =====

--- TRAIN ---
R           : 0.2933
R2          : 0.0860
R2 score    : 0.0860
RMSE        : 0.9473
MSE         : 0.8973
MAPE        : 0.7875
Adj_R2      : 0.0623

--- TEST ---
R           : 0.2308
R2          : 0.0533
R2 score    : 0.0217
RMSE        : 1.0806
MSE         : 1.1677
MAPE        : 1.0029
Adj_R2      : -0.0934

Persamaan:
y = 89.477261 + (0.004546)*C + (0.021745)*E

===== 2 CHANNEL | FOLD 3 =====

--- TRAIN ---
R           : 0.3009
R2          : 0.0905
R2 score    : 0.0905
RMSE        : 0.9444
MSE         : 0.8919
MAPE        : 0.8359
Adj_R2      : 0.0669

--- TEST ---
R           : 0.1858
R2          : 0.0345
R2 score    : 0.0014
RMSE        : 1.0876
MSE         : 1.1829
MAPE        : 0.8400
Adj_R2      : -0.1161

Persamaan:
y = 89.509765 + (0.005883)*C + (0.016824)*E

===== 2 CHANNEL | FOLD 4 =====

--- TRAIN ---
R           : 0.2577
R2          : 0.0664
R2 score    : 0.0664
RMSE        : 0.9566
MSE         : 0.9150
MAPE        : 0.8278
Adj_R2      : 0.0422

--- TEST ---
R           : 0.3089
R2          : 0.0954
R2 score    : 0.0908
RMSE        : 1.0410
MSE         : 1.0837
MAPE        : 0.8646
Adj_R2      : -0.0161

Persamaan:
y = 89.728361 + (0.005117)*C + (0.015241)*E

===== 2 CHANNEL | FOLD 5 =====

--- TRAIN ---
R           : 0.2743
R2          : 0.0752
R2 score    : 0.0752
RMSE        : 0.9915
MSE         : 0.9831
MAPE        : 0.8435
Adj_R2      : 0.0512

--- TEST ---
R           : 0.2667
R2          : 0.0712
R2 score    : 0.0673
RMSE        : 0.9034
MSE         : 0.8161
MAPE        : 0.7965
Adj_R2      : -0.0424

Persamaan:
y = 89.668823 + (0.006304)*C + (0.013586)*E
3 CHANNEL
FITUR : C, E, B

===== 3 CHANNEL | FOLD 1 =====

--- TRAIN ---
R           : 0.2514
R2          : 0.0632
R2 score    : 0.0632
RMSE        : 1.0234
MSE         : 1.0473
MAPE        : 0.8715
Adj_R2      : 0.0262

--- TEST ---
R           : 0.3714
R2          : 0.1379
R2 score    : 0.1041
RMSE        : 0.7459
MSE         : 0.5564
MAPE        : 0.6831
Adj_R2      : -0.0639

Persamaan:
y = 89.714072 + (0.004461)*C + (0.018214)*E - (0.000836)*B

===== 3 CHANNEL | FOLD 2 =====

--- TRAIN ---
R           : 0.2934
R2          : 0.0861
R2 score    : 0.0861
RMSE        : 0.9473
MSE         : 0.8973
MAPE        : 0.7876
Adj_R2      : 0.0500

--- TEST ---
R           : 0.2251
R2          : 0.0507
R2 score    : 0.0191
RMSE        : 1.0821
MSE         : 1.1709
MAPE        : 1.0031
Adj_R2      : -0.1648

Persamaan:
y = 89.489320 + (0.004244)*C + (0.021135)*E + (0.001028)*B

===== 3 CHANNEL | FOLD 3 =====

--- TRAIN ---
R           : 0.3024
R2          : 0.0915
R2 score    : 0.0915
RMSE        : 0.9439
MSE         : 0.8910
MAPE        : 0.8369
Adj_R2      : 0.0556

--- TEST ---
R           : 0.1949
R2          : 0.0380
R2 score    : 0.0034
RMSE        : 1.0866
MSE         : 1.1806
MAPE        : 0.8356
Adj_R2      : -0.1835

Persamaan:
y = 89.450496 + (0.007053)*C + (0.019708)*E - (0.004313)*B

===== 3 CHANNEL | FOLD 4 =====

--- TRAIN ---
R           : 0.2956
R2          : 0.0874
R2 score    : 0.0874
RMSE        : 0.9457
MSE         : 0.8944
MAPE        : 0.8157
Adj_R2      : 0.0514

--- TEST ---
R           : 0.0104
R2          : 0.0001
R2 score    : -0.0395
RMSE        : 1.1131
MSE         : 1.2390
MAPE        : 0.9620
Adj_R2      : -0.2344

Persamaan:
y = 89.607300 + (0.011202)*C + (0.028581)*E - (0.023635)*B

===== 3 CHANNEL | FOLD 5 =====

--- TRAIN ---
R           : 0.2757
R2          : 0.0760
R2 score    : 0.0760
RMSE        : 0.9911
MSE         : 0.9823
MAPE        : 0.8429
Adj_R2      : 0.0395

--- TEST ---
R           : 0.2750
R2          : 0.0756
R2 score    : 0.0719
RMSE        : 0.9012
MSE         : 0.8121
MAPE        : 0.7967
Adj_R2      : -0.1021

Persamaan:
y = 89.609435 + (0.007406)*C + (0.016604)*E - (0.004290)*B
4 CHANNEL
FITUR : C, E, B, F

===== 4 CHANNEL | FOLD 1 =====

--- TRAIN ---
R           : 0.2582
R2          : 0.0667
R2 score    : 0.0667
RMSE        : 1.0215
MSE         : 1.0434
MAPE        : 0.8670
Adj_R2      : 0.0169

--- TEST ---
R           : 0.5017
R2          : 0.2517
R2 score    : 0.1627
RMSE        : 0.7211
MSE         : 0.5200
MAPE        : 0.6460
Adj_R2      : -0.0606

Persamaan:
y = 89.644430 + (0.007829)*C + (0.034928)*E - (0.007636)*B - (0.030895)*F

===== 4 CHANNEL | FOLD 2 =====

--- TRAIN ---
R           : 0.3040
R2          : 0.0924
R2 score    : 0.0924
RMSE        : 0.9440
MSE         : 0.8911
MAPE        : 0.7734
Adj_R2      : 0.0440

--- TEST ---
R           : 0.2687
R2          : 0.0722
R2 score    : 0.0436
RMSE        : 1.0684
MSE         : 1.1416
MAPE        : 0.9909
Adj_R2      : -0.2114

Persamaan:
y = 89.382240 + (0.007980)*C + (0.040282)*E - (0.005894)*B - (0.035774)*F

===== 4 CHANNEL | FOLD 3 =====

--- TRAIN ---
R           : 0.3396
R2          : 0.1153
R2 score    : 0.1153
RMSE        : 0.9315
MSE         : 0.8676
MAPE        : 0.8121
Adj_R2      : 0.0681

--- TEST ---
R           : 0.1735
R2          : 0.0301
R2 score    : -0.0329
RMSE        : 1.1062
MSE         : 1.2236
MAPE        : 0.8470
Adj_R2      : -0.3084

Persamaan:
y = 89.217948 + (0.014823)*C + (0.057908)*E - (0.019156)*B - (0.070178)*F

===== 4 CHANNEL | FOLD 4 =====

--- TRAIN ---
R           : 0.3045
R2          : 0.0928
R2 score    : 0.0928
RMSE        : 0.9430
MSE         : 0.8892
MAPE        : 0.8074
Adj_R2      : 0.0444

--- TEST ---
R           : 0.1017
R2          : 0.0103
R2 score    : 0.0021
RMSE        : 1.0906
MSE         : 1.1894
MAPE        : 0.9155
Adj_R2      : -0.2640

Persamaan:
y = 89.561151 + (0.014635)*C + (0.046354)*E - (0.028839)*B - (0.037482)*F

===== 4 CHANNEL | FOLD 5 =====

--- TRAIN ---
R           : 0.3213
R2          : 0.1032
R2 score    : 0.1032
RMSE        : 0.9764
MSE         : 0.9534
MAPE        : 0.8073
Adj_R2      : 0.0554

--- TEST ---
R           : 0.1545
R2          : 0.0239
R2 score    : -0.0097
RMSE        : 0.9400
MSE         : 0.8835
MAPE        : 0.8258
Adj_R2      : -0.2790

Persamaan:
y = 89.507408 + (0.015139)*C + (0.053527)*E - (0.017297)*B - (0.075163)*F
5 CHANNEL
FITUR : C, E, B, F, L

===== 5 CHANNEL | FOLD 1 =====

--- TRAIN ---
R           : 0.2674
R2          : 0.0715
R2 score    : 0.0715
RMSE        : 1.0188
MSE         : 1.0380
MAPE        : 0.8697
Adj_R2      : 0.0088

--- TEST ---
R           : 0.6161
R2          : 0.3796
R2 score    : 0.2515
RMSE        : 0.6818
MSE         : 0.4649
MAPE        : 0.6167
Adj_R2      : -0.0159

Persamaan:
y = 88.962120 + (0.005885)*C + (0.030115)*E - (0.001691)*B - (0.028791)*F + (0.051845)*L

===== 5 CHANNEL | FOLD 2 =====

--- TRAIN ---
R           : 0.3395
R2          : 0.1152
R2 score    : 0.1152
RMSE        : 0.9320
MSE         : 0.8687
MAPE        : 0.7688
Adj_R2      : 0.0554

--- TEST ---
R           : 0.2608
R2          : 0.0680
R2 score    : 0.0440
RMSE        : 1.0683
MSE         : 1.1412
MAPE        : 1.0065
Adj_R2      : -0.2975

Persamaan:
y = 88.262270 + (0.002500)*C + (0.022689)*E + (0.009186)*B - (0.023976)*F + (0.103431)*L

===== 5 CHANNEL | FOLD 3 =====

--- TRAIN ---
R           : 0.3776
R2          : 0.1426
R2 score    : 0.1426
RMSE        : 0.9170
MSE         : 0.8409
MAPE        : 0.8022
Adj_R2      : 0.0846

--- TEST ---
R           : 0.1686
R2          : 0.0284
R2 score    : -0.0472
RMSE        : 1.1138
MSE         : 1.2406
MAPE        : 0.8474
Adj_R2      : -0.4212

Persamaan:
y = 87.800562 + (0.010889)*C + (0.049527)*E - (0.007445)*B - (0.069582)*F + (0.110595)*L

===== 5 CHANNEL | FOLD 4 =====

--- TRAIN ---
R           : 0.3208
R2          : 0.1029
R2 score    : 0.1029
RMSE        : 0.9377
MSE         : 0.8792
MAPE        : 0.8076
Adj_R2      : 0.0423

--- TEST ---
R           : 0.1941
R2          : 0.0377
R2 score    : 0.0366
RMSE        : 1.0716
MSE         : 1.1483
MAPE        : 0.8993
Adj_R2      : -0.3074

Persamaan:
y = 88.761493 + (0.012075)*C + (0.040386)*E - (0.021777)*B - (0.034499)*F + (0.063328)*L

===== 5 CHANNEL | FOLD 5 =====

--- TRAIN ---
R           : 0.3895
R2          : 0.1517
R2 score    : 0.1517
RMSE        : 0.9496
MSE         : 0.9018
MAPE        : 0.7888
Adj_R2      : 0.0944

--- TEST ---
R           : 0.1461
R2          : 0.0214
R2 score    : -0.2367
RMSE        : 1.0403
MSE         : 1.0822
MAPE        : 0.9012
Adj_R2      : -0.6784

Persamaan:
y = 86.823313 + (0.008739)*C + (0.042851)*E + (0.001709)*B - (0.069877)*F + (0.184218)*L
6 CHANNEL
FITUR : C, E, B, F, L, V

===== 6 CHANNEL | FOLD 1 =====

--- TRAIN ---
R           : 0.3832
R2          : 0.1468
R2 score    : 0.1468
RMSE        : 0.9766
MSE         : 0.9538
MAPE        : 0.8523
Adj_R2      : 0.0767

--- TEST ---
R           : 0.4571
R2          : 0.2090
R2 score    : 0.1794
RMSE        : 0.7139
MSE         : 0.5096
MAPE        : 0.6344
Adj_R2      : -0.1994

Persamaan:
y = 89.386669 - (0.003928)*C + (0.019428)*E + (0.019986)*B - (0.009381)*F + (0.124057)*L - (0.041201)*V

===== 6 CHANNEL | FOLD 2 =====

--- TRAIN ---
R           : 0.4907
R2          : 0.2408
R2 score    : 0.2408
RMSE        : 0.8633
MSE         : 0.7454
MAPE        : 0.7342
Adj_R2      : 0.1784

--- TEST ---
R           : 0.0175
R2          : 0.0003
R2 score    : -0.1613
RMSE        : 1.1774
MSE         : 1.3862
MAPE        : 1.1166
Adj_R2      : -0.6972

Persamaan:
y = 88.354998 - (0.010460)*C + (0.008865)*E + (0.038398)*B - (0.001294)*F + (0.214962)*L - (0.048113)*V

===== 6 CHANNEL | FOLD 3 =====

--- TRAIN ---
R           : 0.4580
R2          : 0.2098
R2 score    : 0.2098
RMSE        : 0.8803
MSE         : 0.7750
MAPE        : 0.7878
Adj_R2      : 0.1448

--- TEST ---
R           : 0.2793
R2          : 0.0780
R2 score    : -0.0114
RMSE        : 1.0946
MSE         : 1.1981
MAPE        : 0.9179
Adj_R2      : -0.4782

Persamaan:
y = 87.876574 + (0.003324)*C + (0.052860)*E + (0.006646)*B - (0.066755)*F + (0.184560)*L - (0.036911)*V

===== 6 CHANNEL | FOLD 4 =====

--- TRAIN ---
R           : 0.3806
R2          : 0.1448
R2 score    : 0.1448
RMSE        : 0.9155
MSE         : 0.8381
MAPE        : 0.8096
Adj_R2      : 0.0745

--- TEST ---
R           : 0.5508
R2          : 0.3034
R2 score    : 0.1793
RMSE        : 0.9890
MSE         : 0.9782
MAPE        : 0.8057
Adj_R2      : -0.1994

Persamaan:
y = 88.886512 + (0.005947)*C + (0.042217)*E - (0.007162)*B - (0.038789)*F + (0.113481)*L - (0.026245)*V

===== 6 CHANNEL | FOLD 5 =====

--- TRAIN ---
R           : 0.4159
R2          : 0.1729
R2 score    : 0.1729
RMSE        : 0.9377
MSE         : 0.8792
MAPE        : 0.7972
Adj_R2      : 0.1050

--- TEST ---
R           : 0.3354
R2          : 0.1125
R2 score    : 0.0197
RMSE        : 0.9262
MSE         : 0.8578
MAPE        : 0.8486
Adj_R2      : -0.4327

Persamaan:
y = 87.142225 + (0.004732)*C + (0.045801)*E + (0.007857)*B - (0.064048)*F + (0.205485)*L - (0.022683)*V
7 CHANNEL
FITUR : C, E, B, F, L, V, G

===== 7 CHANNEL | FOLD 1 =====

--- TRAIN ---
R           : 0.4841
R2          : 0.2343
R2 score    : 0.2343
RMSE        : 0.9252
MSE         : 0.8560
MAPE        : 0.8194
Adj_R2      : 0.1599

--- TEST ---
R           : 0.5786
R2          : 0.3348
R2 score    : 0.2660
RMSE        : 0.6752
MSE         : 0.4558
MAPE        : 0.5691
Adj_R2      : -0.1621

Persamaan:
y = 89.235183 - (0.010101)*C + (0.005609)*E + (0.047331)*B - (0.008191)*F + (0.073795)*L - (0.065678)*V + (0.078119)*G

===== 7 CHANNEL | FOLD 2 =====

--- TRAIN ---
R           : 0.6230
R2          : 0.3881
R2 score    : 0.3881
RMSE        : 0.7751
MSE         : 0.6008
MAPE        : 0.6621
Adj_R2      : 0.3286

--- TEST ---
R           : 0.0382
R2          : 0.0015
R2 score    : -0.3403
RMSE        : 1.2649
MSE         : 1.5999
MAPE        : 1.1697
Adj_R2      : -1.1221

Persamaan:
y = 88.131112 - (0.020044)*C + (0.004819)*E + (0.070684)*B + (0.001319)*F + (0.112431)*L - (0.074623)*V + (0.099301)*G

===== 7 CHANNEL | FOLD 3 =====

--- TRAIN ---
R           : 0.5041
R2          : 0.2541
R2 score    : 0.2541
RMSE        : 0.8553
MSE         : 0.7315
MAPE        : 0.7590
Adj_R2      : 0.1816

--- TEST ---
R           : 0.4790
R2          : 0.2294
R2 score    : 0.2195
RMSE        : 0.9616
MSE         : 0.9246
MAPE        : 0.8043
Adj_R2      : -0.2358

Persamaan:
y = 87.956127 - (0.001173)*C + (0.034412)*E + (0.029333)*B - (0.057826)*F + (0.116837)*L - (0.047199)*V + (0.061587)*G

===== 7 CHANNEL | FOLD 4 =====

--- TRAIN ---
R           : 0.4945
R2          : 0.2446
R2 score    : 0.2446
RMSE        : 0.8605
MSE         : 0.7404
MAPE        : 0.7628
Adj_R2      : 0.1711

--- TEST ---
R           : 0.5389
R2          : 0.2905
R2 score    : 0.2133
RMSE        : 0.9683
MSE         : 0.9377
MAPE        : 0.8204
Adj_R2      : -0.2456

Persamaan:
y = 88.800413 - (0.000423)*C + (0.029132)*E + (0.017149)*B - (0.034959)*F + (0.059220)*L - (0.046248)*V + (0.074176)*G

===== 7 CHANNEL | FOLD 5 =====

--- TRAIN ---
R           : 0.5005
R2          : 0.2505
R2 score    : 0.2505
RMSE        : 0.8926
MSE         : 0.7968
MAPE        : 0.7746
Adj_R2      : 0.1776

--- TEST ---
R           : 0.4680
R2          : 0.2190
R2 score    : 0.1624
RMSE        : 0.8561
MSE         : 0.7329
MAPE        : 0.7596
Adj_R2      : -0.3262

Persamaan:
y = 87.310496 - (0.000985)*C + (0.029209)*E + (0.034301)*B - (0.061842)*F + (0.134048)*L - (0.042174)*V + (0.074640)*G
8 CHANNEL
FITUR : C, E, B, F, L, V, G, I

===== 8 CHANNEL | FOLD 1 =====

--- TRAIN ---
R           : 0.5679
R2          : 0.3225
R2 score    : 0.3225
RMSE        : 0.8703
MSE         : 0.7573
MAPE        : 0.7710
Adj_R2      : 0.2462

--- TEST ---
R           : 0.5463
R2          : 0.2985
R2 score    : 0.2101
RMSE        : 0.7004
MSE         : 0.4905
MAPE        : 0.6166
Adj_R2      : -0.3643

Persamaan:
y = 90.642752 - (0.007750)*C + (0.026525)*E + (0.055609)*B - (0.027920)*F - (0.281623)*L - (0.067349)*V + (0.051545)*G + (0.071353)*I

===== 8 CHANNEL | FOLD 2 =====

--- TRAIN ---
R           : 0.6680
R2          : 0.4462
R2 score    : 0.4462
RMSE        : 0.7374
MSE         : 0.5437
MAPE        : 0.6561
Adj_R2      : 0.3838

--- TEST ---
R           : 0.1812
R2          : 0.0328
R2 score    : -0.2484
RMSE        : 1.2207
MSE         : 1.4902
MAPE        : 1.0927
Adj_R2      : -1.1564

Persamaan:
y = 89.210322 - (0.018704)*C + (0.018867)*E + (0.081178)*B - (0.011419)*F - (0.177590)*L - (0.078386)*V + (0.087705)*G + (0.054812)*I

===== 8 CHANNEL | FOLD 3 =====

--- TRAIN ---
R           : 0.5867
R2          : 0.3443
R2 score    : 0.3443
RMSE        : 0.8019
MSE         : 0.6431
MAPE        : 0.6972
Adj_R2      : 0.2704

--- TEST ---
R           : 0.4881
R2          : 0.2382
R2 score    : 0.2108
RMSE        : 0.9669
MSE         : 0.9349
MAPE        : 0.8499
Adj_R2      : -0.3632

Persamaan:
y = 89.187081 + (0.001227)*C + (0.044129)*E + (0.042558)*B - (0.065774)*F - (0.232041)*L - (0.048476)*V + (0.048059)*G + (0.065782)*I

===== 8 CHANNEL | FOLD 4 =====

--- TRAIN ---
R           : 0.5499
R2          : 0.3024
R2 score    : 0.3024
RMSE        : 0.8269
MSE         : 0.6837
MAPE        : 0.7296
Adj_R2      : 0.2238

--- TEST ---
R           : 0.6021
R2          : 0.3625
R2 score    : 0.3268
RMSE        : 0.8958
MSE         : 0.8024
MAPE        : 0.7770
Adj_R2      : -0.1628

Persamaan:
y = 89.699433 - (0.001125)*C + (0.033100)*E + (0.032082)*B - (0.033690)*F - (0.199869)*L - (0.051326)*V + (0.060635)*G + (0.054160)*I

===== 8 CHANNEL | FOLD 5 =====

--- TRAIN ---
R           : 0.5574
R2          : 0.3107
R2 score    : 0.3107
RMSE        : 0.8561
MSE         : 0.7328
MAPE        : 0.7386
Adj_R2      : 0.2330

--- TEST ---
R           : 0.5696
R2          : 0.3245
R2 score    : 0.3088
RMSE        : 0.7777
MSE         : 0.6048
MAPE        : 0.7012
Adj_R2      : -0.1938

Persamaan:
y = 88.401842 - (0.000968)*C + (0.042482)*E + (0.044144)*B - (0.065030)*F - (0.138332)*L - (0.047464)*V + (0.044722)*G + (0.058695)*I
9 CHANNEL
FITUR : C, E, B, F, L, V, G, I, A

===== 9 CHANNEL | FOLD 1 =====

--- TRAIN ---
R           : 0.5962
R2          : 0.3555
R2 score    : 0.3555
RMSE        : 0.8488
MSE         : 0.7205
MAPE        : 0.7299
Adj_R2      : 0.2726

--- TEST ---
R           : 0.4576
R2          : 0.2094
R2 score    : 0.0374
RMSE        : 0.7732
MSE         : 0.5978
MAPE        : 0.6732
Adj_R2      : -0.8290

Persamaan:
y = 89.454843 - (0.001695)*C + (0.044224)*E + (0.026209)*B - (0.059628)*F - (0.155804)*L - (0.088290)*V + (0.081704)*G + (0.030995)*I + (0.011392)*A

===== 9 CHANNEL | FOLD 2 =====

--- TRAIN ---
R           : 0.6867
R2          : 0.4716
R2 score    : 0.4716
RMSE        : 0.7203
MSE         : 0.5188
MAPE        : 0.6470
Adj_R2      : 0.4037

--- TEST ---
R           : 0.1987
R2          : 0.0395
R2 score    : -0.2994
RMSE        : 1.2454
MSE         : 1.5511
MAPE        : 1.0649
Adj_R2      : -1.4689

Persamaan:
y = 88.442580 - (0.014812)*C + (0.036252)*E + (0.059455)*B - (0.032948)*F - (0.119475)*L - (0.094103)*V + (0.109853)*G + (0.030191)*I + (0.008297)*A

===== 9 CHANNEL | FOLD 3 =====

--- TRAIN ---
R           : 0.5982
R2          : 0.3578
R2 score    : 0.3578
RMSE        : 0.7936
MSE         : 0.6298
MAPE        : 0.6884
Adj_R2      : 0.2753

--- TEST ---
R           : 0.5173
R2          : 0.2676
R2 score    : 0.2288
RMSE        : 0.9558
MSE         : 0.9136
MAPE        : 0.8351
Adj_R2      : -0.4653

Persamaan:
y = 88.644911 + (0.003742)*C + (0.054551)*E + (0.026381)*B - (0.080369)*F - (0.173024)*L - (0.059011)*V + (0.059977)*G + (0.046042)*I + (0.006124)*A

===== 9 CHANNEL | FOLD 4 =====

--- TRAIN ---
R           : 0.5606
R2          : 0.3143
R2 score    : 0.3143
RMSE        : 0.8198
MSE         : 0.6721

,Jumlah_Channel,Channel,Fold,Train_R,Train_R2,Train_R2score,Train_RMSE,Train_MSE,Train_MAPE,Train_Adj_R2,Test_R,Test_R2,Test_R2score,Test_RMSE,Test_MSE,Test_MAPE,Test_Adj_R2,Persamaan
0,1,C,1,0.209713,0.043979,0.043979,1.033804,1.068750,0.884452,0.031723,0.341664,0.116734,0.082398,0.754893,0.569863,0.659984,0.031420,y = 90.451459 + (0.006472)*C
1,1,C,2,0.239330,0.057279,0.057279,0.962058,0.925555,0.796087,0.045193,0.268311,0.071991,0.040732,1.070067,1.145043,1.003434,-0.012560,y = 90.348437 + (0.007373)*C
2,1,C,3,0.261241,0.068247,0.068247,0.955916,0.913776,0.833425,0.056301,0.158807,0.025220,-0.006512,1.091944,1.192341,0.877743,-0.062429,y = 90.229844 + (0.007721)*C
3,1,C,4,0.224601,0.050446,0.050446,0.964697,0.930640,0.829042,0.038272,0.274876,0.075557,0.059380,1.058840,1.121143,0.889998,0.007123,y = 90.405114 + (0.006505)*C
4,1,C,5,0.251964,0.063486,0.063486,0.997796,0.995597,0.851583,0.051479,0.174712,0.030524,0.017538,0.927198,0.859696,0.788712,-0.037044,y = 90.250488 + (0.007772)*C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,18,"C, E, B, F, L, V, G, I, A, H, J, R, W, D, S, K...",1,0.781634,0.610952,0.610952,0.659487,0.434923,0.590182,0.496151,0.368281,0.135631,-0.483090,0.959714,0.921051,0.830304,-27.178710,y = 81.092038 + (0.015017)*C + (0.009208)*E - ...
86,18,"C, E, B, F, L, V, G, I, A, H, J, R, W, D, S, K...",2,0.786845,0.619126,0.619126,0.611506,0.373939,0.543515,0.506737,0.485561,0.235769,0.171203,0.994638,0.989305,0.827101,-14.747148,y = 81.350884 + (0.005860)*C + (0.022591)*E + ...
87,18,"C, E, B, F, L, V, G, I, A, H, J, R, W, D, S, K...",3,0.760243,0.577970,0.577970,0.643341,0.413888,0.564935,0.453436,0.643633,0.414263,0.392279,0.848482,0.719922,0.762897,-10.546701,y = 81.337486 + (0.017276)*C + (0.035518)*E - ...
88,18,"C, E, B, F, L, V, G, I, A, H, J, R, W, D, S, K...",4,0.755277,0.570443,0.570443,0.648845,0.421000,0.565069,0.443688,0.682143,0.465319,0.408078,0.839954,0.705523,0.774364,-10.246525,y = 82.780969 + (0.015241)*C + (0.043296)*E - ...
89,18,"C, E, B, F, L, V, G, I, A, H, J, R, W, D, S, K...",5,0.737672,0.544159,0.544159,0.696131,0.484598,0.617610,0.409649,0.771783,0.595649,0.442643,0.698363,0.487710,0.594796,-9.589778,y = 78.896957 + (0.011022)*C + (0.045014)*E - ...